### PR TITLE
Cache CQ indexes

### PR DESCRIPTION
**Pull request by kocolosk**
The coupling between `ddoc_cache` and `mango` is inelegant here but I erred on the side of keeping the patch set small.

BugzID: 4270

### CODE REVIEW

**Comment by kocolosk** [comment]
See cloudant/mango#12

**Comment by iilyak** [comment]
IMHO I think we shouldn't introduce dependency on mango.
How about `open_doc(DbName, atom())`. Since DocId cannot be atom we can use this fact to pass a callback module. I.e. you would do:

```
list(Db) ->
  {ok, Indexes} = ddoc_cache_opener:open_doc(Db, mango),
  Indexes.
```

You also would add `mango_cache.erl` into mongo app. You would implement `recover` callback there. 
WDYT?

**Comment by kocolosk** [comment]
I think it can work. It'll be important to register each callback module with the ddoc_cache_opener so it can evict properly.

**Comment by iilyak** [comment]
You can add a clause at https://github.com/cloudant/ddoc_cache/blob/42707-cache-mango-ddocs/src/ddoc_cache_opener.erl#L191
(Handler) when is_atom(Handler) ->
   ets_lru:remove(?CACHE, {DbName, Handler}))

**Comment by kocolosk** [comment]
Closing in favor of #6 which implements the approach suggested by @iilyak

**Pull request closed without merging**
