### PR TITLE
Refactored cache to support optional document revisions

### PR DESCRIPTION
**Pull request by ghost**
After some hunting and subsequent extinguishing of a cache eviction bug, this new code seems to work. Reviewers should specifically look at the use of `ets_lru:match`. Depending on how often it's called it might be wise to avoid the current gen_server call that it costs and create a match_d version. The other focus should be the new revision api `ddoc_cache:open_doc/3`.

I'll leave this for review while I finish testing the changes required to start using this in certain places to avoid doc chatter over the wire. In the mean time, please tear this apart as I'm sure it could be improved.

### CODE REVIEW

**Comment by davisp** [comment]
Definitely a fan of how you refactored the API and implementation of ddoc_cache.erl in 491f9e8

**Comment by davisp** [comment]
Ooh. Super fond of how you sidestepped the issue of opening a doc without a revision using match_latest.

**Comment by davisp** [comment]
And I totally fucked up my PR comments by commenting on commits...

In other news, I really like how you changed things. Both how you solved the merging of the open versions with and without a revision as well as the reformulation of the APIs and moving logic around.

+1 after addressing the commit comments.

**Comment by dschoettle** [comment]
This was a great way to get the day started!  Love it PD.

**Pull request merged**
